# Generated by Django 4.1.5 on 2023-01-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(max_length=250)),
                ("character_name", models.CharField(max_length=250)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("is_private", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("summary", models.CharField(blank=True, max_length=250, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "directed_by",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("running_time", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("is_private", models.BooleanField(default=False)),
            ],
        ),
    ]
